# Generated by Django 4.2.7 on 2025-12-23 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('min_weight', models.FloatField()),
                ('max_weight', models.FloatField()),
                ('feed_size', models.FloatField()),
                ('feeding_times', models.IntegerField()),
                ('adaptation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FeedingInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_temp', models.FloatField()),
                ('fish_length', models.FloatField()),
                ('fish_weight', models.FloatField()),
                ('fish_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeding.pond')),
            ],
        ),
    ]
